### ISSUE TITLE
Deep Doze forced

### ISSUE THREAD

**Issue by chatdeschroedinger** [easz/doze-tweak#2]
hi @easz thank you for this great analysis! Could not find anything close to it anywhere else.

I am trying to make my device enter deep doze mode almost immediately after the screen is turned off. However, I can only make it go to light sleep mode.

This is the result from my `adb shell dumpsys deviceidle`
Settings:
    light_after_inactive_to=+3m0s0ms
    light_pre_idle_to=+3m0s0ms
    light_idle_to=+5m0s0ms
    light_idle_factor=2.0
    light_max_idle_to=+15m0s0ms
    light_idle_maintenance_min_budget=+1m0s0ms
    light_idle_maintenance_max_budget=+5m0s0ms
    min_light_maintenance_time=+5s0ms
    min_deep_maintenance_time=+30s0ms
    inactive_to=+30m0s0ms
    sensing_to=+4m0s0ms
    locating_to=+30s0ms
    location_accuracy=20.0m
    motion_inactive_to=+10m0s0ms
    idle_after_inactive_to=+30m0s0ms
    idle_pending_to=+5m0s0ms
    max_idle_pending_to=+10m0s0ms
    idle_pending_factor=2.0
    idle_to=+1h0m0s0ms
    max_idle_to=+6h0m0s0ms
    idle_factor=2.0

Then I use the following settings:
`adb shell settings put global device_idle_constants inactive_to=1000,motion_inactive_to=1000,idle_after_inactive_to=1000,light_after_inactive_to=2000,light_pre_idle_to=2000,light_max_idle_to=86400000,light_idle_to=1800000,light_idle_factor=1.5,sensing_to=1000,locating_to=1000,location_accuracy=10000,idle_pending_to=1000,max_idle_pending_to=1000`

But the device does not enter deep doze....can this be because it has no motion sensor? (see below)

mLightEnabled=true  mDeepEnabled=true
  mForceIdle=false
  mMotionSensor=null
  mScreenOn=false
  mScreenLocked=false
  mNetworkConnected=true
  mCharging=false
  mMotionActive=false
  mNotMoving=false
  mLocating=false mHasGps=true mHasNetwork=false mLocated=false
  mState=INACTIVE mLightState=IDLE
  mInactiveTimeout=+1s0ms
  mNextIdleDelay=+45m0s0ms
  mNextLightAlarmTime=+28m38s109ms
  mCurIdleBudget=+1m0s0ms

**Comment by easz** [comment]
yes, what I understood is indeed that the deep doze depends on motion sensor unfortunately. Light doze would be the best what you can achieve.

**Comment by chatdeschroedinger** [comment]
Ok. And there is no possibility that it uses this SMD?

I will try to force the device into deep doze mode by using the force-idle command by including the app in my AOSP build and giving it these privileges.

Or did you try to modify the DeviceIdleController.java before?

**Comment by easz** [comment]
To be honest at the moment I only tried to use existing pre-built Android system w/o building customized one by myself.  Modifying the `DeviceIdleController.java` could be a solution but may break something else.

SMD would be used as fallback by default :)
https://github.com/aosp-mirror/platform_frameworks_base/blob/nougat-release/services/core/java/com/android/server/DeviceIdleController.java#L1379

Of course SMD behaves differently from usual motion sensor https://source.android.com/devices/sensors/sensor-types
